@echo off
echo Starting Frontend Server...
cd /d "C:\Users\Core5\Desktop\subscription test\LMS-PROTOTYPE-2\LMS-main\client"
echo Installing dependencies...
call npm install
echo Starting development server...
call npm run dev -- --host 0.0.0.0 --port 5175 --strictPort
pause
