const { AssessmentError } = require('./errors');

/**
 * Optional picture attached to a question (diagram, graph, figure, map...).
 *
 * The bytes live in the private file store (never in the database, never under a public URL).
 * A question refers to its picture by an opaque key generated by the store. The key is returned
 * only to the teacher who uploaded it; students never see keys - they fetch the picture of a
 * question they are allowed to see, and the server looks the key up.
 *
 * Validation is by CONTENT: the declared type and the file name are not trusted.
 */
const MAX_IMAGE_BYTES = 2 * 1024 * 1024;
const IMAGE_TYPES = Object.freeze({ png: 'image/png', jpg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp' });
const IMAGE_EXTENSIONS = Object.freeze(Object.keys(IMAGE_TYPES));
const IMAGE_CONTENT_TYPES = Object.freeze(Object.values(IMAGE_TYPES));
const IMAGE_KEY = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.(png|jpg|gif|webp)$/;

const startsWith = (buffer, bytes, offset = 0) => bytes.every((b, i) => buffer[offset + i] === b);

/** The image format found in the bytes themselves, or null. SVG and other formats are not accepted. */
function detectImageExtension(buffer) {
  if (!Buffer.isBuffer(buffer) || buffer.length < 12) return null;
  if (startsWith(buffer, [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) return 'png';
  if (startsWith(buffer, [0xff, 0xd8, 0xff])) return 'jpg';
  if (startsWith(buffer, [0x47, 0x49, 0x46, 0x38]) && (buffer[4] === 0x37 || buffer[4] === 0x39) && buffer[5] === 0x61) return 'gif';
  if (startsWith(buffer, [0x52, 0x49, 0x46, 0x46]) && startsWith(buffer, [0x57, 0x45, 0x42, 0x50], 8)) return 'webp';
  return null;
}

const invalid = (code, message, statusCode = 400) => new AssessmentError(code, message, { statusCode });

/** @returns {{ buffer: Buffer, extension: string, contentType: string }} */
function validateImageUpload({ buffer, contentType }) {
  if (!Buffer.isBuffer(buffer) || buffer.length === 0) {
    throw invalid('IMAGE_REQUIRED', 'Choose a PNG, JPG, GIF or WebP image to upload.');
  }
  if (buffer.length > MAX_IMAGE_BYTES) {
    throw invalid('IMAGE_TOO_LARGE', 'The image is too large. The limit is 2 MB.', 413);
  }
  const extension = detectImageExtension(buffer);
  if (!extension) {
    throw invalid('IMAGE_TYPE_NOT_ALLOWED', 'Only PNG, JPG, GIF and WebP images can be attached to a question.', 415);
  }
  const declared = String(contentType || '').split(';')[0].trim().toLowerCase();
  if (declared !== IMAGE_TYPES[extension]) {
    throw invalid('IMAGE_TYPE_MISMATCH', 'The file does not match its declared image type.', 415);
  }
  return { buffer, extension, contentType: IMAGE_TYPES[extension] };
}

/** Field validation for a question payload: undefined/null/'' = no picture; otherwise a store key. */
function parseImageKey(value, field, details) {
  if (value === undefined || value === null || value === '') return null;
  if (typeof value !== 'string' || !IMAGE_KEY.test(value)) {
    details.push({ field, code: 'INVALID_IMAGE' });
    return null;
  }
  return value;
}

const contentTypeOfKey = (key) => IMAGE_TYPES[String(key).split('.').pop()] || 'application/octet-stream';

module.exports = {
  MAX_IMAGE_BYTES, IMAGE_EXTENSIONS, IMAGE_CONTENT_TYPES, IMAGE_KEY,
  detectImageExtension, validateImageUpload, parseImageKey, contentTypeOfKey,
};
